name: JavaScript Linter (JSHint)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install JSHint
        run: sudo apt-get update && sudo apt-get install -y jshint

      - name: Run JSHint
        run: |
          if ls *.js 1> /dev/null 2>&1; then
            jshint *.js
          else
            echo "No JavaScript files found. Skipping JSHint."
          fi
